### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by bangseongmin** [bangseongmin/sns-service#40]
* [ ] Repository Layer를 JPA로 리팩토링
* [ ] 팔로워가 100만명인 유저의 게시물 작성 성능 테스트
   * [ ] 비동기 큐를 통해 개선
   * [ ] Mixed Push / Pull Model
* [ ] 로그인 / 팔로우 승인, 취소, 댓글 구현
* [ ] MySQL Master / Slave
* [ ] 파티셔닝

**Comment by bangseongmin** [comment]
후기

## 1단계. 리팩토링
JDBC 템플릿을 이용해 구현을 하여 불필요한 중복 코드가 너무나도 많기 때문에 JPA로 전환해서 리팩토링을 해보자.
JPA가 아니더라도 중복된 코드를 Generic을 통해 제거를 하든 별도의 모듈을 통해 제거를 하든 해보자.

## 2단계. 성능 테스트
팔로워가 100만명인 유저의 게시물 작성 성능 테스트를 해보자.
EasyRandom을 통해서 레코드를 쭉 쌓고 SQL 서버를 모니터링하면서 보았었는데 `nGrinder`와 같은 부하테스트를 자동화 해줄 수 있는 도구를 사용해보자. 

팔로우가 100만명인 사용자가 게시물을 작성하면 현재 프로젝트에서는 게시물을 작성하는데 시간이 엄청 오래걸릴 것입니다.
왜냐하면 게시물 작성과 타임라인을 전달하는 트랜잭션이 하나로 묶여있기 때문입니다. 

개선할 수 있는 방법
1. 비동기 큐를 이용한 방법
2. Mixed Push / Pull 모델

## 3 단계. 기능 강화
로그인 / 팔로우 승인, 취소 / 댓글 구현을 구현해보자. 

추가적으로 이론적인 학습이 필요합니다. 

## 이론 학습
- MySQL에 Master/Slave를 통해 READ의 부하를 줄일 수 있습니다. 어떻게 동작하는지 까지 공부해보자.
- 데이터가 많아졌을 때 관리할 수 있는 기본적인 방법인 파티셔닝을 공부해보자.
